theme: jekyll-theme-leap-day

#can configure most Jekyll settings, such as your site's theme and plugins, by editing  _config.yml file.


title: [Welcome-to-Marcelo]
description: [Hi, I am Marcelo]

collections:
  experiences:
    output: true 
  projects:
    output: true
  posts:
    future: true

defaults: 
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: "content"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "content"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "content"
  - scope:
      path: ""
    values:
      layout: "default"

description: Marcelo is a Johns Hopkins University student majoring in computer science

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

highlighter: rouge

permalink: /:categories/:title

paginate: 8
paginate_path: "/blog/page:num/"
